### ISSUE TITLE
Variablen werden nicht angelegt / Laden der Systemvariablen funktioniert nicht

### ISSUE THREAD

**Issue by RealWinny** [PhilippEngler/eufy-security-hm#1]
Zunächst mal vielen Dank für dieses Tool! Das ist wirklich eine hilfreiche Sache. Ich kriege es allerdings bei mir noch nicht zum Laufen. 

Es beginnt im Prinzip schon bei den Variablen. Folgende Probleme/Fragen:

1. Der Inhalt der Dateien "setup_getIDs.txt" und "setup_setCommonData.txt" ist unter Programme / Skript testen ins Eingabefenster zu kopieren und auszuführen, richtig? Eine Datei nach der anderen oder beide hintereinander? Ich habe es einzeln gemacht und bei mir wurden fünf Variablen angelegt (eufyCurrentState, eufyLastConnectionResult, eufyLastConnectionTime, eufyLastLinkUpdateTime, eufyLastStatusUpdateTime). Wenn ich mir die Textdateien so anschaue, sollten es doch aber mehr sein. Was ist z.B. mit eufyCameraImageURL? Die wird bei mir nicht angelegt. Wo könnte der Fehler sein?
Ich kann die Variablen jetzt natürlich auch einfach manuell anlegen. Die Intention ist ja aber vermutlich, dass es auch mit den Textdateien funktioniert.

2. Im AddOn unter Einstellungen ganz unten steht in der Regel nur "Laden der Systemvariablen..." ohne Veränderung. Irgendwann stand da auch mal was von einem Fehler, zuletzt aber nur noch ersteres. Ich hatte das AddOn zwischenzeitlich auch schon mal deinstalliert und wieder installiert. Das Phänomen bleibt aber gleich. Was kann da hängen? Kann ich irgendwelche Logs zur Verfügung stellen?

<img width="1440" alt="Screenshot Einstellungen" src="https://user-images.githubusercontent.com/28679778/105576807-ac683780-5d75-11eb-80f4-e618b2f2c01a.png">

**CCU/RaspberryMatic:**
 - Device: CCU3
 - OS: Rasperymatic 3.55.5.20201226
 - Installed AddOns: CUxD, HAP-Homematik, RedMatic

**Comment by PhilippEngler** [comment]
Die Punkte 1 und 2 hängen zusammen. Bei den Systemvariablen, die nicht angelegt wurden, handelt es sich um gerätespezifische Systemvariablen. Deren Namen enthalten zusätzlich die jeweilige Seriennummer des Gerätes.

Meiner Meinung nach schlägt die Anmeldung bei eufy fehl.
Überprüfe bitte folgende Punkte:
- Handelt es sich um einen Account nur für das Addon und ohne Zwei-Faktor-Authentifizierung?
- Sind die Zugangsdaten korrekt eingegeben?
- Sind Fehler in den Logdateien vorhanden (einsehbar über den vorletzten Reiter "Logdateien")?
- Werden die Basisstationen beim Aufruf der API im Browser (http://_IP-DER-CCU_:52789/getBases) angezeigt?

**Comment by RealWinny** [comment]
Ok, bei dem Account lag schon mal definitiv ein Fehler vor. Ich Held habe zwar einen zweiten Account (nur für das AddOn) angelegt. Darin waren meine Geräte aber natürlich noch nicht verknüpft. Das habe ich nun nachgeholt. Wenn ich mich direkt über den Browser auf http://mysecurity.eufylife.com einlogge, ist alles da. 2FA wurde **nicht** aktiviert.
Verstehe ich das System dahingehend richtig? Ich habe jetzt zwei Accounts und in jedem sind all meine Eufy-Geräte verknüpft. Wenn jetzt ein neues Gerät hinzukommt (bspw. eine weitere Kamera), muss ich die ja auch wieder zunächst im einen Account und dann nochmals im anderen Account einrichten, korrekt?

Zurück zur CCU: Der oben angegeben Befehl (http://IP-DER-CCU:52789/getBases) liefert leider kein Ergebnis. Mir ist dabei auch noch aufgefallen, dass in der setup_getIDs.txt folgendes steht:
`! Geräte abrufen
system.Exec("curl --max-time 10 'http://127.0.0.1:52789/getDevices'", &res, &err);`

Warum diese IP? Passt das?

Und hier noch der Log:
[Log EufySecAddOn 20210123.txt](https://github.com/PhilippEngler/eufy-security-hm/files/5860322/Log.EufySecAddOn.20210123.txt)

**Comment by PhilippEngler** [comment]
Dann ist das mit dem Account jetzt soweit in Ordnung.

Wenn unter Einstellungen die Mailadresse hinterlegt ist, passt jetzt nur das Token nicht mehr (durch die Anmeldung im Webportal).

Zur Zeit am einfachsten wäre es, folgende Befehle in der WebUI unter "Skript testen" auszuführen:
`system.Exec("rm /usr/local/addons/eufySecurity/config.ini");`
`system.Exec("rm /var/log/eufySecurity.log");`
`system.Exec("rm /var/log/eufySecurity.err");`
Mit der ersten Zeile wird die bisherige Config-Datei gelöscht (da ist das Token mit enthalten), mit der zweiten und dritten Zeile werden die beiden Logdateien gelöscht (dann sind nur noch neue Nachrichten enthalten).

Anschließend bitte noch das Addon neustarten (in der WebUI unter "Einstellungen" > "Systemsteuerung" > "Zusatzsoftware" im Bereich des eufy SECURITY Addons auf "Neustart" klicken.

Jetzt können auf der Einstellungsseite des Addons die Zugangsdaten nochmal eingeben und gespeichert werden. Dann sollte unter Geräte alle Geräte aufgeführt sein.

_Zu der Frage nach den eufy-Accounts:_ Es existieren jetzt (mindestens) zwei Accounts. Der Account, mit dem das System ursprünglich eingerichtet wurde, ist der Administrator. Dort müssen auch zukünftig alle neuen Geräte eingerichtet werden. Anschließend werden diese dann für den/die weiteren Accounts "freigegeben". In diesem Addon erscheinen diese dann automatisch, lediglich eventuelle Systemvariablen müssen wieder angelegt werden. Dies geht aber über das Script, bereits vorhandene Variablen werden nicht neu erstellt oder geändert.

_Zur Frage nach der IP-Adresse:_ Da das Skript auf der CCU selbst ausgeführt wird, kann die lokale IP-Adresse (127.0.0.1 oder localhost) genutzt werden. Wenn über einen Webbrowser auf die API zugegriffen werden soll, geht dies nur mit der IP-Adresse der CCU.

**Comment by RealWinny** [comment]
Jawohl, hat alles funktioniert. Danke für den Support, ein Dankeschön folgt!

**Comment by PhilippEngler** [comment]
Sehr schön, Danke für die Rückmeldung.
Ich bin bereits dabei, einige Verbesserungen (Token löschen, Error-Handling des Server, ...) vorzunehmen.

**Comment by RealWinny** [comment]
Ich finde jetzt allerdings keinen Sponsor-Button auf der Seite. Du kannst mir gerne mal eine Paypal-Adresse zum Zwecke einer unterstützenden Zuwendung zukommen lassen...

**Comment by PhilippEngler** [comment]
Ich habe den Sponsor-Butten jetzt hinzugefügt.
Einige Probleme, die Du gestern gehabt hat, werden jetzt besser abgefangen. Ich teste jetzt noch etwas, spätestens am Freitag wird eine neue Version bereeit stehen.
Vielen Dank nochmals für Deine Reückmeldungen.
