### ISSUE TITLE
S120

### ISSUE THREAD

**Issue by David83L** [PhilippEngler/eufy-security-hm#12]
Bitte die Cam s120 hinzufügen 

viele liebe danke im Voraus

**Comment by PhilippEngler** [comment]
Die v3.0.0 sollte die Solar Wall Light Cam S120 (T84A0) bereits grundlegend unterstützen. Für die komplette Implementation würde ich die JSON-Dateien, die auf der Einstellungsseite des Gerätes generiert werden können, benötigen. Falls die S120 ohne Verbindung zur HomeBase genutzt wird, zusätzlich bitte auch die der S120-Station.
