### ISSUE TITLE
Support for Eufy Solocam S340

### ISSUE THREAD

**Issue by Zolle04** [PhilippEngler/eufy-security-hm#13]
It would be nice to get support for S340 (T8170). thx

**Comment by PhilippEngler** [comment]
The device should be compatible since v3.0.0. If you are running an CCU3 with original firmware from eq-3, you must upgrade to RaspberryMatic to use v3.0.0. I am not able to back-port this to get it working with the original firmware from eq-3.

If you receiving the messages in the device settings, that the device is not fully compatible, please generate the json-files linked in the message and send them to me. Then I can finish the implementation of the device.

**Comment by Zolle04** [comment]
I'm running on Raspberrymatic. The indoor cam shows the settings as expected but the S340 have problems. 
![image](https://github.com/user-attachments/assets/9c76a9a3-985c-4a94-92a8-2e18765ceffb)

**Comment by PhilippEngler** [comment]
Could you please open the web developer tools (on Firefox for example click on the "hamburger menu" than 'More tools' and 'Web Developer Tools'. There, please select "Console".

Now please reload the device page and try to access the settings again. Than there should be logged an error there. Can you please post this error here?

**Comment by Zolle04** [comment]
![image](https://github.com/user-attachments/assets/7b66d7f6-c5f2-47e9-956e-f8d35e133b77)

**Comment by PhilippEngler** [comment]
Thank you. Also for making the screenshots. Could you please get the JSON-files from the following link and send them to me (please replace `<CCU3>` with the address of your ccu and `<SERIAL>` with the serial of your S340 (T8170))?
- `http://<CCU3>:52789/getStationPropertiesTruncated/<SERIAL>`
- `http://<CCU3>:52789/getStationPropertiesMetadata/<SERIAL>`
- `http://<CCU3>:52789/getDevicePropertiesTruncated/<SERIAL>`
- `http://<CCU3>:52789/getDevicePropertiesMetadata/<SERIAL>`

I have found the place where it comes to problem, but I have no idea why. Maybe I need this files again, if the v3.0.2 will be available (either today or next weekend).

**Comment by Zolle04** [comment]
see attachments
[getDevicePropertiesMetadata.txt](https://github.com/user-attachments/files/16487445/getDevicePropertiesMetadata.txt)
[getDevicePropertiesTruncated.txt](https://github.com/user-attachments/files/16487446/getDevicePropertiesTruncated.txt)
[getStationPropertiesMetadata.txt](https://github.com/user-attachments/files/16487447/getStationPropertiesMetadata.txt)
[getStationPropertiesTruncated.txt](https://github.com/user-attachments/files/16487448/getStationPropertiesTruncated.txt)

anyway: thx for your quick response

**Comment by PhilippEngler** [comment]
The new v3.0.2 is now available. Please check if the device settings are shown with the new version. Anyway, your T8170 should now be shown only once on the device page (the "4G LTE Kameras" section should now be gone).
And also I would like to ask you to send me the four files above from the new version, than I hopefully can implement the full support for T8170.

**Comment by Zolle04** [comment]
![image](https://github.com/user-attachments/assets/bf209c8f-7e4e-41b7-8e22-051b70516a46)
![image](https://github.com/user-attachments/assets/37c170c9-cd35-4a80-8bfe-87bc6adbcf49)
4G Device is gone :-)
Properties now available. But no full support

**Comment by PhilippEngler** [comment]
Great. Than I would like to ask you if you can create the four files again with the new v3.0.2 and send them to me. Than I can fully integrate the device.

**Comment by Zolle04** [comment]
[getStationPropertiesTruncated.txt](https://github.com/user-attachments/files/16488408/getStationPropertiesTruncated.txt)
[getStationPropertiesMetadata.txt](https://github.com/user-attachments/files/16488409/getStationPropertiesMetadata.txt)
[getDevicePropertiesTruncated.txt](https://github.com/user-attachments/files/16488410/getDevicePropertiesTruncated.txt)
[getDevicePropertiesMetadata.txt](https://github.com/user-attachments/files/16488411/getDevicePropertiesMetadata.txt)

**Comment by PhilippEngler** [comment]
Thank you. It will take some days and I will come back to you...

**Comment by PhilippEngler** [comment]
So far it looks really nice, but I have some questions a it would be fine if you can answer them:
- Can you please tell me your settings for timezone and time format (12/24h) from the original app (station | common settings | time settings)? In the files above you have the timezone "Africa/Abidjan" and 12h time format. Are these the correct settings?
- Also I would like to now, what the app is showing for storage values (capacity, used and free space amount).
- And if you find the time, please check if the add-ons webui shows the correct state for the battery (not charging/solar/charging)?

The other settings seems to be already correctly implemented.

**Comment by Zolle04** [comment]
- 12h format is correct. But timezone is set to Berlin (GMT+2)
- 240 MB used, Overall 7,1 GB

so there will be a Version?

**Comment by Zolle04** [comment]
seems to be connection issue. It states: No P2P Connection, although everything is fine after restarting the camera.

**Comment by PhilippEngler** [comment]
The timezone is an interesting issue, because the timezone in your json is `GMT+02:00|1.1375` where it must be `CET-1CEST,M3.5.0,M10.5.0/3|1.1375` for Berlin.

The issue with the P2P connection I have already seen in your json files. Are there any info in the log files? As this is the first battery-powered solo device for this add-on, this must not be an error - maybe this is due to energy saving. With the next version (coming hopefully in a couple of days), there will be some changes related to this issue and it would be great, if you can do some tests.

**Comment by Zolle04** [comment]
2024-08-05 18:57:53.808 ERROR [addon] Error occured at setGuardMode: Failed to communicate with station.
2024-08-05 18:59:12.349 ERROR [addon] Error occured at setGuardMode: Failed to switch mode for station T8170T1024160C35.
2024-08-05 19:01:13.232 INFO  [http]  Connected to station T8170T1024160C35 on host 192.168.0.164 and port 17411
2024-08-05 19:01:13.502 WARN  [p2p]   Command aged out from send queue for station T8170T1024160C35 {
  commandType: 1350,
  nestedCommandType: 1306,
  channel: 0,
  ageing: 13447338,
  maxAgeing: 120000

2024-08-11 11:27:11.360 WARN  [p2p]   Command aged out from send queue for station T8170T1024160C35 {
  commandType: 1144,
  nestedCommandType: undefined,
  channel: 255,
  ageing: 173628866,
  maxAgeing: 120000
}
2024-08-11 11:27:12.157 INFO  [http]  Disconnected from station T8170T1024160C35
2024-08-11 11:27:12.158 INFO  [addon] Event "Close": station: T8170T1024160C35
2024-08-11 11:31:08.916 ERROR [p2p]   All address lookup tentatives failed. { stationSN: 'T8170T1024160C35' }
2024-08-11 11:31:08.918 INFO  [http]  Timeout connecting to station T8170T1024160C35
2024-08-11 16:03:38.535 WARN  [p2p]   Tried all hosts, no connection could be established to station T8170T1024160C35.
2024-08-11 16:03:38.538 INFO  [http]  Timeout connecting to station T8170T1024160C35
2024-08-11 16:09:35.882 ERROR [addon] Error occured at setGuardMode: Failed to switch mode for station T8170T1024160C35.

**Comment by Zolle04** [comment]
I've generated Trace Level Logs. I have no problems if you need further infos...

**Comment by PhilippEngler** [comment]
I have uploaded a beta release ([v3.0.3-b1](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.0.3-b1)). Could you please send me the generated trace log files (the mail address you can find in the `package.json` file). Do you have any other device than the T8170? **Please note that in the log files contains the full serial numbers and other personal data.**

**Comment by Zolle04** [comment]
I have send you the logs. The version seems to work. First tests are successful:-)

**Comment by Zolle04** [comment]
![image](https://github.com/user-attachments/assets/a7dbdb4c-79b4-422b-a848-7067c80bcd14)
Reaction have a problem. No execution of the program.
![image](https://github.com/user-attachments/assets/89ac57bb-dcca-4a4c-a9bd-e2911664574f)

**Comment by PhilippEngler** [comment]
I have seen the files right now, thank you. We will see what happens, there are some messages that the T8170 have got another ip address. Have you fixed the ip address in your dhcp server? In the case, the p2p connection will get lost again, please also try the setting "fast connection" instead of "local only".

**Comment by Zolle04** [comment]
I've a Fritzbox which manage the DNS. I fixed the IP Adress in the seetings. So I expect no unforced switch of the IP

**Comment by Zolle04** [comment]
I've double checked the DNS settings. As I said. It is fixed and it is the same IP Adress since I start the ticket

**Comment by PhilippEngler** [comment]
> Reaction have a problem. No execution of the program.

I have checked it, here there is no problem. Error 401 indicate a authentication error. If the ip you have entered is the ip of the ccu the addon is running on, you can try to use `localhost`.

**Comment by Zolle04** [comment]
localhost works 👍

**Comment by PhilippEngler** [comment]
> I've double checked the DNS settings. As I said. It is fixed and it is the same IP Adress since I start the ticket

Fine, I will check it. In the log, there are two or three ip addresses (if you want to check by yourself, search for `LOCAL_LOOKUP_RESP - Unwanted device was found, don't connect to it` in the log you sent me first).

**Comment by Zolle04** [comment]
Does the API supports the use of predefined camera positions?

**Comment by PhilippEngler** [comment]
> Does the API supports the use of predefined camera positions?

Not sure, but I believe it is not supported at the moment. Anyway, I have ordered a T8170 for testing purposes...

**Comment by PhilippEngler** [comment]
> Does the API supports the use of predefined camera positions?

The client supports this. I have it for now implemented with a T8416 (IndoorCam S350), where I have found some other problems. The next step is to implement the T8170. If the T8170 supports presets this in the same manner as the T8460, presets will be available...

**Comment by Zolle04** [comment]
Unfortunately the addon hangs 
![image](https://github.com/user-attachments/assets/070f20c3-91a1-4c0c-90a5-5149141c6ff8)
I'm not able to restart the service

**Comment by PhilippEngler** [comment]
You can restart the addon also via the ccu webui. Go to "Systemsteuerung" | "Zusatzsoftware", there is a restart button. Please have also a look at [CCU Addon für eufy Security Kameras - HomeMatic Forum](https://homematic-forum.de/forum/viewtopic.php?f=18&t=64416)...

**Comment by PhilippEngler** [comment]
With the [v3.1.0-b1](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.0-b1) the T8170 work now as a standalone device with this add-on. On the info-page you will also find how you can use the preset-positions by scripts...

**Comment by Zolle04** [comment]
I've some stability issues. But I test the new version.Thx anyway
