### ISSUE TITLE
Addon not starting after updating to 3.1.0

### ISSUE THREAD

**Issue by cRemE-fReSh** [PhilippEngler/eufy-security-hm#14]
**Describe the bug**
After updating to Version 3.1.0 (from 3.0.2) the addon won't work any longer.

**To Reproduce**
1. Install the update
2. Open the config screen of the addon
3. Refer to the error message:

**Expected behavior**
Addon works ;-)

**Screenshots**
![2024-09-04 09_23_34-eufy Security AddOn für HomeMatic – Mozilla Firefox](https://github.com/user-attachments/assets/57b23635-b4ef-4131-b7db-a723fb709f5a)

**Desktop/Mobile Device (please complete the following information):**
 - OS: [e.g. Windows, Linux, iOS]
 - Browser [e.g. edge, firefox, chrome, safari]

**CCU/RaspberryMatic (please complete the following information):**
 - Device: Virtual Machine, x64
 - OS: linux_x64
 - Platform: Raspberrymatic 3.77.7.20240826
 - Installed AddOns: CUx-Daemon

**Additional context**
Restart of the device did not solve the issue.
LogFiles attached.
[eufySecurity_CF-RM_20240904_092400_client.log](https://github.com/user-attachments/files/16862419/eufySecurity_CF-RM_20240904_092400_client.log)
[eufySecurity_CF-RM_20240904_092355.log](https://github.com/user-attachments/files/16862420/eufySecurity_CF-RM_20240904_092355.log)

**Comment by cRemE-fReSh** [comment]
Solved by downloading and reuploading the configuration.

**Comment by PhilippEngler** [comment]
It would be helpful if you can provide the `eufySecurity.err` file. There should be a hint to the error.

**Comment by cRemE-fReSh** [comment]
I didn't upload the file because it was empty. No entry!
