### ISSUE TITLE
Problem with documentation

### ISSUE THREAD

**Issue by mik55** [PhilippEngler/eufy-security-hm#17]
Hello Philipp, thank you very much for this addon. 
I have been running a Debmatic installation for our house for a long time. You write in the documentation that your addon also runs under Debmatic (The addon will run .... debmatic). 
How do I install Debmatic? 
Alex Reinert only included a few addons in his documentation and unfortunately your addon is not in the Apt repository.
Greetings
Michael

**Comment by PhilippEngler** [comment]
Hello Michael,

I'm sorry, but the `README.md` is currently a little bit outdated (will be updated soon). I will have to check with debmatic, but the current v3.0-branch will not be compatible with piVCCU (and I'm afraid, this will also be valid for debmatic) - the reason is the same as for the original CCU3 firmware provided by eq-3.

Best
Philipp

**Comment by mik55** [comment]
Thank you for the answer. 
Do you see a chance for the adapter on the debmatic?
regards
Michael

**Comment by PhilippEngler** [comment]
The good news: The addon can run under debmatic.
The not so good news: At the moment, there is a need to do this manually and the log files are not available on the web ui.

As I have noticed, there is a need to create a deb-file for installation. I will have to look in it deeper, if and how the support of debmatic is possible.

**Comment by PhilippEngler** [comment]
Short update: I got it managed to create the deb files for arm32, arm64 and amd64.

Unfortunately, debmatic relies on tcl8.2 and this is also the cause the log file page is not working. Updating to tcl8.6 (which is shipped with RaspberryMatic) will break the debmatic webUI. But I think, I have a solution in place. If this will work, I can tomorrow provide a solution you can test.

**Comment by PhilippEngler** [comment]
@mik55: I have added the deb-files to the v3.1.1-rc2 at the end of the release notes under the downloads for RaspberryMatic. Please try it and report any problems during installation. Besides the restart of the add-on via webui, all functions should work.

[v3.1.1-rc2](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.1-rc2)

**Comment by PhilippEngler** [comment]
The deb files are now available within the new release [v3.1.1](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.1). In case of problems when installing/uninstalling/updateing please open a new issue.
