### ISSUE TITLE
Support for motion sensor

### ISSUE THREAD

**Issue by Zolle04** [PhilippEngler/eufy-security-hm#18]
**Is your feature request related to a problem? Please describe.**
Connect motion detection to Homematic

**Describe the solution you'd like**
Option to execute Homematic program on motion detection

**Please name the device**
https://www.eufy.com/eu-de/products/t8910?var)

**CCU/RaspberryMatic (please complete the following information):**
 - Device: [e.g. CCU3, RaspberryMatic]
 - OS: [e.g. 3.55.5]
 - Platform: [only valid for RaspberryMatic, e.g. arm32, arm64, amd64]

**Comment by PhilippEngler** [comment]
This might be possible. The device should already been visible in the device list, I will need the json-files generated in the settings of the device (yellow box on top of the device settings modal), than we will see what is possible.

**Comment by PhilippEngler** [comment]
Please try [v3.1.1-b4](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.1-b4). There should be some log events if motions are detected. If this is the case, please send the log entries to me. And please send me the json-files (DeviceProperties and DevicePropertiesMetadata) to get it working with the webui.

**Comment by Zolle04** [comment]
The hardware arrives next week

**Comment by Zolle04** [comment]
[eufySecurity_CCU2-_20241103_073303.log](https://github.com/user-attachments/files/17609567/eufySecurity_CCU2-_20241103_073303.log)
[DevicePropertiesMetaMotionSensor.json](https://github.com/user-attachments/files/17609570/DevicePropertiesMetaMotionSensor.json)
[DevicePropertiesMotionSensor.json](https://github.com/user-attachments/files/17609571/DevicePropertiesMotionSensor.json)

7:29 was a test detection

**Comment by Zolle04** [comment]
[MotionSensor.txt](https://github.com/user-attachments/files/17609839/MotionSensor.txt)
here is the info

**Comment by PhilippEngler** [comment]
Thanks, it seems that it could work. Could you please send me the json from the following link:
`http://<IP_CCU>:52789/getDeviceParams/SERIAL_MOTION_SENSOR`

Thanks in advance.

**Comment by PhilippEngler** [comment]
Should work with the next version coming within the next days...

![T8910_Main](https://github.com/user-attachments/assets/338997db-28c7-4a50-93ab-bc279e715c89)

![T8910_Detail](https://github.com/user-attachments/assets/484c1a97-8651-4239-af12-e3e36591d524)

**Comment by PhilippEngler** [comment]
The [v3.1.1-rc1](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.1-rc1) is available. You can check it now. Please keep in mind, that the motion event will only be send via notifications, not over the p2p connection, so that a working internet connection is required for the interactions and there will be a delay of 5 to 10 seconds.

**Comment by Zolle04** [comment]
![image](https://github.com/user-attachments/assets/fdb3cc0c-b001-424f-968e-e0fd02489a25)
There is an error opening the device settings of the camera.
![image](https://github.com/user-attachments/assets/5fc459c8-d2cf-410c-b677-f9ea44b0af33).
The settings of the motion sensor works.

**Comment by PhilippEngler** [comment]
Thanks, error found. will be fixed today afternoon...

**Comment by PhilippEngler** [comment]
[v3.1.1-rc2](https://github.com/PhilippEngler/eufy-security-hm/releases/tag/v3.1.1-rc2) should fix this issue.

**Comment by PhilippEngler** [comment]
> The settings of the motion sensor works.

Thank you, I have overseen this information. Does the interaction also works?

**Comment by Zolle04** [comment]
A first test was succesful

**Comment by PhilippEngler** [comment]
Sounds good. I will close this issue.
