### ISSUE TITLE
Fehler bei der Ermittlung der Einstellungen

### ISSUE THREAD

**Issue by andispammonyer** [PhilippEngler/eufy-security-hm#4]
Ich nutze deine eufy Addon (1.5.2) mit drei EufyCam 2 Pro und Homebase.
Die Kameras funktionieren in der Eufy App einwandfrei.

Das Addon hatte ich vor ein paar Wochen eingerichtet und es hat anfangs funktioniert (Systemvariablen wurden aktualisiert und ich konnte per HM Skript die Modis wechseln). Doch neuerdings und ohne Änderungen in dem Addon vorzunehmen, funktioniert es nicht mehr. Wenn ich das Addon Webinterface aufrufe, laden die Einstellungen und schlagen dann nach einer Weile fehl mit: "Fehler bei der Ermittlung der Einstellungen".
Neustart des Addons oder der CCU (RaspberryMatic) bringen keinen Erfolg. 
Ich musste vor einer Woche ein CCU Backup einspielen vom Vortag. Sollte eigentlich bedeuten, dass die EufyAddon Einstellungen nicht geändert wurden.

Log Dateien kann ich nicht bereitstellen, weil auch hier ein Fehler kommt: "Fehler beim Laden der Protokolldatei" und "Fehler beim Laden der Fehlerprotokolldatei"

Ich werde das Addon nun deinstallieren und neu einrichten.

**Comment by andispammonyer** [comment]
Habe zwischen Deinstallation und Neuinstallation kein CCU Neustart ausgeführt (wurde nicht verlangt), aber das hat jedenfalls nicht funktioniert. Das Addon bringt noch immer dieselben Fehler.
Zudem ist auf der Einstellungsseite alles ausgegraut, sodass ich kein neuen Account und Einstellungen vornehmen kann.
![Eufy-Fehler](https://user-images.githubusercontent.com/68514976/132124250-d1ce5058-7076-42b7-9b38-b9669da43516.JPG)

**Comment by andispammonyer** [comment]
Neustart nach Deinstallation und Neustart nach Installation bringt genauso wenig.
Ich kann einfach keine neue Mail-Adresse eingeben. 
Ich habe zum Glück damals die funktionierende Konfig heruntergeladen. 
Doch selbst wenn ich diese config.ini auf der CCU überschreibe und den Dienst oder sogar die CCU neustarte, bleibt es bei "Fehler bei der Ermittlung der Einstellungen"

**Comment by PhilippEngler** [comment]
Wie hast Du das Backup zurückgespielt? In ein zurückgesetztes System oder einfach das Backup über das laufende System drübergespielt?
Falls das Backup in ein zurückgesetztes System zurückgespielt wurde, muss das Addon danach neu installiert werden.

Wenn Du die Logdateien nicht lesen kannst, deutet eigentlich alles auf einen nicht laufenden Service hin.

Da Du ja anscheinend per ssh auf Dein System kommst, könntest Du mal in die Logdateien /var/log/eufySecurity.log und /var/log/eufySecurity.err schauen. Vielleicht bringt das etwas Licht ins Dunkle....

**Comment by andispammonyer** [comment]
Hallo,

ich habe ein .sbk Backup über die WebUI eingespielt. Welcher Variante entspricht das? 
Ich habe allerings die Neuinstallation schon ausprobiert ohne Erfolg.

In der ERR Datei steht drin:
2021-09-05 20:42:06 - P2PClientProtocol.lookup(): station: T80xxxxxx95 - All address lookup tentatives failed.

In der LOG Datei steht drin:
2021-09-05 20:41:49 - Configfile needs Stage2 update to version 7...
2021-09-05 20:41:49 -  rename 'api_update_state_active' to 'api_update_state_intervall_active'.
2021-09-05 20:41:49 -  adding 'api_update_state_event_active'.
2021-09-05 20:41:49 - ...Stage2 update to version 7 finished.
2021-09-05 20:41:49 - eufy_security_hm version 1.5.2 (0.8.3)
2021-09-05 20:41:49 -   Platform: linux_arm
2021-09-05 20:41:49 -   Node: v14.17.2
2021-09-05 20:41:49 - Starting http server...
2021-09-05 20:41:49 - ...started. http listening on port '52789'
2021-09-05 20:41:49 - Starting https server...
2021-09-05 20:41:49 - ...started. https listening on port '52790'
2021-09-05 20:41:51 - Setting up scheduled tasks...
2021-09-05 20:41:51 -   scheduling getState disabled in settings.
2021-09-05 20:41:51 -   scheduling getLinks disabled in settings.
2021-09-05 20:41:51 - ...done setting up scheduled tasks.
2021-09-05 20:42:08 - INFO: Disconnected from station T80xxxxx95
2021-09-05 20:42:13 - INFO: Connected to station T80xxx95 on host 192.168.178.45 and port 19581
2021-09-05 20:42:15 - INFO: Connected to station T80xxxxx95 on host 192.168.178.45 and port 18605

**Comment by PhilippEngler** [comment]
Das sieht komisch aus. Die Configfile Stage1/2 Updates sollten eigentlich nur einmal laufen, irgenwo klemmt da etwas mit Deiner Configdatei.

Du könntest mit einem Browser versuchen, folgendes aufzurufen:
http://<IP_DER_CCU>:52789/getConfig
und die Ausgabe [**ohne deine Zugangsdaten**] hier posten.

Die schnellere und einfachste Variante wäre es, die config-Datei zu löschen und neu anzufangen:
1. den Service per ssh stoppen ("/usr/local/etc/config/rc.d/eufySecurity stop")
2. die config.ini-Datei unter "/usr/local/addons/eufySecurity/config.ini" löschen
3. den Service per ssh wieder starten ("/usr/local/etc/config/rc.d/eufySecurity start")

Nun wird eine neue, leere config-Datei angelegt und die Einstellungen sollten funktionieren.
Alternativ könntest Du mit einem Browser versuchen, folgendes aufzurufen:
http://<IP_DER_CCU>:52789/getConfig
und die Ausgabe [**ohne deine Zugangsdaten**] hier posten.

**Comment by andispammonyer** [comment]
Danke das werde ich am Wochenende ausprobieren.
Obwohl die Fehler vom Addon in der WebUI noch bestehen, ging es heute, dass die CCU Skriptaufrufe (Away und Home) funktioniert haben?! Versteh wer will.

**Comment by PhilippEngler** [comment]
Laut der Logdatei ist das Addon mit Deiner Basis verbunden und auch der API-Server läuft. Somit funktioniert der Statuswechsel.
Ich vermute, dass Probleme mit der Konfigrationsdatei gibt - welcher Art auch immer (Berechtigungen, ... wobei er dann eigentlich einen Fehler werfern muss).

**Comment by andispammonyer** [comment]
Hallo,

hier der Auszug von getConfig

{"success":true,"data":[{"username":"xx@xx.de","password":"xx","api_http_active":"true","api_http_port":"52789","api_https_active":"true","api_https_port":"52790","api_https_key_file":"/usr/local/etc/config/server.pem","api_https_cert_file":"/usr/local/etc/config/server.pem","api_connection_type":"1","api_udp_local_static_ports_active":"false","api_udp_local_static_ports_T80xx95":"","api_use_system_variables":"true","api_camera_default_image":"","api_camera_default_video":"","api_use_update_state_event":"false","api_use_update_state_intervall":"false","api_update_state_timespan":"15","api_use_update_links":"false","api_use_update_links_only_when_active":"false","api_update_links_timespan":"15","api_log_level":"1"}]}

Nach stoppen, löschen der config.ini und starten kommt das hier bei getConfig raus:

{"success":true,"data":[{"username":"","password":"","api_http_active":"true","api_http_port":"52789","api_https_active":"true","api_https_port":"52790","api_https_key_file":"/usr/local/etc/config/server.pem","api_https_cert_file":"/usr/local/etc/config/server.pem","api_connection_type":"1","api_udp_local_static_ports_active":"falseapi_use_system_variables=false","api_use_system_variables":"undefined","api_camera_default_image":"","api_camera_default_video":"","api_use_update_state_event":"false","api_use_update_state_intervall":"false","api_update_state_timespan":"15","api_use_update_links":"true","api_use_update_links_only_when_active":"undefined","api_update_links_timespan":"15","api_log_level":"0"}]}

WebUI vom Addon zeigt keine Unterschiede. Noch immer kommt Fehler und unter Konfiguration ist alles ausgegraut.

Gebe ich dann in der neuen config.ini nur Mail und PW an sieht der getConfig Auszug so aus:

{"success":true,"data":[{"username":"xx@xx.de","password":"xx","api_http_active":"true","api_http_port":"52789","api_https_active":"true","api_https_port":"52790","api_https_key_file":"/usr/local/etc/config/server.pem","api_https_cert_file":"/usr/local/etc/config/server.pem","api_connection_type":"1","api_udp_local_static_ports_active":"falseapi_use_system_variables=false","api_udp_local_static_ports_T80xx95":"","api_use_system_variables":"undefined","api_camera_default_image":"","api_camera_default_video":"","api_use_update_state_event":"false","api_use_update_state_intervall":"false","api_update_state_timespan":"15","api_use_update_links":"true","api_use_update_links_only_when_active":"undefined","api_update_links_timespan":"15","api_log_level":"0"}]}

**Comment by andispammonyer** [comment]
Errorlog sagt in der letzten Zeile:
2021-09-15 23:19:54 - P2PClientProtocol.lookup(): station: T80xx95 - All address lookup tentatives failed.

Normales Log:
2021-09-15 23:19:36 - eufy_security_hm version 1.5.2 (0.8.3)
2021-09-15 23:19:36 -   Platform: linux_arm
2021-09-15 23:19:36 -   Node: v14.17.2
2021-09-15 23:19:36 - Starting http server...
2021-09-15 23:19:36 - ...started. http listening on port '52789'
2021-09-15 23:19:36 - Starting https server...
2021-09-15 23:19:36 - ...started. https listening on port '52790'
2021-09-15 23:19:40 - Setting up scheduled tasks...
2021-09-15 23:19:40 -   scheduling getState disabled in settings.
2021-09-15 23:19:40 -   getLibrary scheduled (runs every 15 minutes).
2021-09-15 23:19:40 - ...done setting up scheduled tasks.

**Comment by andispammonyer** [comment]
Die Geräteübersicht geht nach wie vor nicht. Auch die Aktualisierung einiger Systemvariablen nicht.
Ich kann aber immerhin über Skripte den Away oder Home Modus in der Eufy-Zentrale schalten.
![Eufy Gerate](https://user-images.githubusercontent.com/68514976/133513240-c8ddb64d-0372-4bf5-a607-457256b286fd.JPG)

Hast du jetzt noch eine weitere Idee was man ausprobieren könnte? Vor dem Backup einspielen, hatte alles mal funktioniert, da bin ich mir sehr sicher.

**Comment by PhilippEngler** [comment]
Wir kommen der Sache näher, glaube ich. Es wird die config.ini falsch angelegt.
- Beende mal bitte den Service ("/usr/local/etc/config/rc.d/eufySecurity stop").
- Suche in der config.ini nach dem Eintrag "api_udp_local_static_ports_active". (Meiner Meinung nach müsste dies bei Dir eine laaange Zeile sein)
- Drücke bitte einfach hinter "api_udp_local_static_ports_active=false" die ENTER-Taste, so dass der nächste Eintrag ("api_use_system_variables") in einer neuen Zeile beginnt.
- Starte den Service neu ("/usr/local/etc/config/rc.d/eufySecurity start").

Damit sollte auf jedenfall die Einstellungsseite wieder funktionieren.

**Comment by andispammonyer** [comment]
Anbei meine config.ini
[config.ini.txt](https://github.com/PhilippEngler/eufy-security-hm/files/7190666/config.ini.txt)
Darin gibt es keine lange Zeile bei der Zeilenumbruch fehlt, zumal "api_use_system_variables" nicht direkt auf "api_udp_local_static_ports_active" folgt.
Was mich am meisten stutzig macht, ist der Umstand dass ich durch Re-installation den Fehler nicht weg bekomme. Folglich muss irgendwo nach dem Deinstallieren ein Rest verbleiben. Könnte das eine Fährte sein?

**Comment by PhilippEngler** [comment]
Die Reihenfolge in der Config-Datei spielt keine Rolle, es ist aber trotzdem komisch, dass das so ersetzt wird.
Wenn Du das immer vom gleichen Rechner/Browser ausprobiert hast, könnte es vielleicht helfen, den Cache zu löschen, denn Deine Config funktionioniert bei mir hier ganz wunderbar.
Beim Deinstallieren werden alle Verzeichnisse komplett gelöscht, da bleibt keine Config-Datei o.ä. zurück.

**Comment by andispammonyer** [comment]
Ich habe heute den Edge genutzt und da ist der Fehler nicht vorhanden. Liegt also tatsächlich am Cache (oder Browser Firefox).
Solved. Vielen vielen Dank für deinen Support
