### ISSUE TITLE
Falscher Status

### ISSUE THREAD

**Issue by HalliHansen** [PhilippEngler/eufy-security-hm#5]
Guten Tag aus Hannover,

Zunächst vielen Dank für das Addon…sieht alles toll aus und hat einen hohen Mehrwert…

ABER: momentan habe ich arge Problem mit der State-Variable. Es wird immer der letzte Modus angezeigt. Wechsel ich per App von abwesend auf zuhause, wird „aktiviert“ angezeigt. Wechsel ich von dort auf abwesend, wird „zu Hause“ angezeigt…

Woran kann das liegen?

**Comment by PhilippEngler** [comment]
Hallo,

das könnte evntuell damit zusammenhängen, dass der Statuswechsel u.U. nicht richtig erkannt wurde. Dies sollte mit der v1.5.5 behoben worden sein. Nach dem Update bitte ausprobieren und eventuell zurückmelden.

Viele Grüße
