### ISSUE TITLE
Statuswechsel und Speichern neuer Einstellungen nicht mögich

### ISSUE THREAD

**Issue by RealWinny** [PhilippEngler/eufy-security-hm#6]
Hallo, ich habe neulich per Zufall festgestellt, dass meine Eufy-Homebase den Status nicht mehr wechselt. Ich wechsle per Homematic normal täglich zwischen "abwesend" und "deaktiviert" hin und her. 

Ich habe in der Zwischenzeit mehrere Updates der CCU sowie des Add-Ons vorgenommen und kann jetzt dummerweise nicht sagen, bis wann alles funktioniert hat und ab wann nicht mehr.

Folgende Auffälligkeiten gibt es:
- Möchte ich manuell per Mausklick im Add-On den Status der Homebase ändern, funktioniert dies nicht und es erscheint die Fehlermeldung "Bei Änderung des Status ist ein Fehler aufgetreten". 
- In den Einstellungen des Add-Ons ist das Feld "Standort des eufy Security Accounts" sowie der "UDP Port" rot hervorgehoben. Egal welche Eingaben ich vornehme, beim Klick auf "Einstellungen speichern" erscheint die Fehlermeldung "Bei dem Speichern der Einstellungen ist ein Fehler aufgetreten". 

Die Log-Datei meldet "Address lookup failed." 

Log- und Protokolldatei sind anbei.
[log und err.zip](https://github.com/PhilippEngler/eufy-security-hm/files/7723250/log.und.err.zip)

Vielen Dank für die Unterstützung!

Sonstiges:
 - Device: CCU3
 - OS: 3.61.5.20211113
 - Installed AddOns: Eufy Security AddOn 1.5.5

**Comment by PhilippEngler** [comment]
Hallo,

das mit dem Speichern ist ein Fehler und wird am Wochenende gefixt sein.
Bei dem Problem mit dem Statuswechsel gehe ich davon aus, dass zum einen die Firewall der CCU aktiv ist und zum anderen, dass der UDP-Port leer ist. Der UDP-Port kann dann am Wochenende wieder gespeichert werden (genauso wie die Region, obwohl diese gar nicht leer sein dürfte), dann sollte der Statuswechsel auch wieder mit aktiver Firewall funktionieren.

Viele Grüße

**Comment by RealWinny** [comment]
> Bei dem Problem mit dem Statuswechsel gehe ich davon aus, dass zum einen die Firewall der CCU aktiv ist und zum anderen, dass der UDP-Port leer ist. 
> 

Ja, korrekt, die Firewall ist aktiv, allerdings sind natürlich entsprechende Ports freigegeben. Das hat je eine Weile so funktioniert. Sorry, hab dann nicht mitbekommen, dass ich etwas umstellen müsste. Freue mich auf das Update!

**Comment by PhilippEngler** [comment]
Nein, Du hättest nichts umstellen müssen, die neuen Einstellungen werden automatisch mit default-Werten angelegt (hier: Region).
Steht im Feld UDP-Port etwas drin? Wenn ja, was? Denn das Feld dürfte gar nicht rot sein.
Ansonsten müsste ohne Firewall bis zum Wochenende der Statuswechsel funktionieren.

**Comment by RealWinny** [comment]
So schaut es bei mir aus:
![Screenshot UDP](https://user-images.githubusercontent.com/28679778/146389474-b3d498b5-c158-44e1-abad-10934fc3700e.png)

**Comment by PhilippEngler** [comment]
Die Version 1.5.6 ist verfügar und nun sollten die Einstellungen wieder gespeichert werden. Wenn Du den Port neu eingibst, müsste dann auch trotz aktivierter Firewall die Verbindung zur HomeBase wieder hergestellt werden können.

**Comment by RealWinny** [comment]
Jo, top! Scheint alles zu funktionieren. Vielen Dank!
