### ISSUE TITLE
GitHub release download links not working

### ISSUE THREAD

**Issue by alexbde** [PhilippEngler/eufy-security-hm#7]
**Describe the bug**
Starting with release 1.7.0, the download links on the GitHub release page are no longer working.

**To Reproduce**
1. Go to https://github.com/PhilippEngler/eufy-security-hm/releases
2. Scroll down to "Please choose the installation file according to your hardware"
3. Click on one of the provided download links ending in `-v1.7.0.tar.gz` (or above)
4. See error 404 Not found

**Expected behavior**
The download links are working :)

**Screenshots**
<img width="706" alt="Bildschirmfoto 2023-05-22 um 13 50 54" src="https://github.com/PhilippEngler/eufy-security-hm/assets/17784818/f4a955b6-b8c5-4e22-b47f-bdf7b9d2c598">

**Additional context**
The url in the links provided are ending in `-v1.7.0.tar.gz`, but the files attached under assets are ending in `-1.7.0.tar.gz` (no `v` prefix).

**Comment by PhilippEngler** [comment]
Should be fixed now. Thanks.
