### ISSUE TITLE
eufyCurrentState shows "unbekannt" for custom2 station mode

### ISSUE THREAD

**Issue by alexbde** [PhilippEngler/eufy-security-hm#8]
**Describe the bug**
Setting the station mode (via app manually or via `setMode` endpoint) to `custom2` sets system variable `eufyCurrentState` to `unbekannt`. Setting it to `custom1` leads to `eufyCurrentState` being `personalisiert`.

**To Reproduce**
1. Execute `system.Exec("curl http://127.0.0.1:52789/setMode/custom2 &");` or similar
2. Go to CCU > Status und Bedienung > Systemvariablen
4. See system variable `eufyCurrentState` set to `unbekannt`

**Expected behavior**
The value of the `eufyCurrentState` system variable matches the `mode` parameter of the `setMode` endpoint, e. g. `mode=custom1` => `eufyCurrentState=custom1`, `mode=custom2` => `eufyCurrentState=custom2`, etc.

**Desktop/Mobile Device:**
All devices.

**CCU/RaspberryMatic:**
 - Device: CCU3
 - OS: 3.69.7
 - Installed AddOns: XML-API, NEO SERVER, eufy SECURITY

**Comment by PhilippEngler** [comment]
Will be fixed in next version.

**Comment by PhilippEngler** [comment]
Problem is solved in v2.1.1. The result will now be `personalisiert` for all custom modes, like it should be from the beginning.
